const { color } = require("./color");

module.exports = {
  formInput: {
    width: "80%",
    height: 45,
    backgroundColor: color.white,
    borderRadius: 10,
    marginVertical: 10,
    paddingHorizontal: 15,
    paddingVertical: 10,
    fontSize: 16,
  },
  formHead: {
    elevation: 8,
    fontSize: 30,
    color: color.black,
    textAlign: "center",
    fontWeight: "bold",
  },
  notecss: {
    fontSize: 20,
    color: color.black,
    textAlign: "center",
    fontWeight: "bold",
  },
  formHead2: {
    fontSize: 20,
    color: color.black,
    textAlign: "center",
    // fontWeight: 'bold',
    // backgroundColor: '#FFFF66',
  },
  formHead3: {
    fontSize: 20,
    // backgroundColor: 'white',
    color: color.black,
    textAlign: "center",
    fontWeight: "400",
    padding: 10,
    borderRadius: 10,
    width: "80%",
    marginVertical: 10,
  },
  formTextLinkRight: {
    color: color.black,
    fontSize: 17,
    textAlign: "right",
    marginVertical: 10,
    width: "80%",
  },
  formTextLinkCenter: {
    color: color.black,
    fontSize: 15,
    textAlign: "center",
    marginVertical: 5,
    width: "80%",
  },
  formButton: {
    width: "80%",
    backgroundColor: color.white,
    borderRadius: 10,
    //borderColor: color.black,
    //borderWidth: 1,
    fontSize: 25,
    fontWeight: "bold",
    color: color.black,
    textAlign: "center",
    paddingVertical: 7,
    marginVertical: 10,
  },
};
